name: Recolectar datos BiZi
on:
  workflow_dispatch:
  schedule:
    - cron: */30 * * * *
jobs:
  recolectar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
        name: Run requirements
      - run: python src/snapshots.py
        name: Run Workflow
      - name: Guardar snapshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/snapshots
          git commit -m "Nuevo snapshot" || echo "No hay cambios para guardar"
          git push
permissions:
  contents: write
